image:
  file: .gitpod.dockerfile
tasks:
  tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y postgresql-13 postgresql-client-13
      # Modify PostgreSQL config to run on port 5433
      sudo sed -i "s/#port = 5432/port = 5433/" /etc/postgresql/13/main/postgresql.conf
      sudo service postgresql start
  command: |
      sudo service postgresql start  # Ensure PostgreSQL starts on port 5433
      . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
