image:
  file: .gitpod.dockerfile
tasks:
  init:
    - sudo apt-get update
    - sudo apt-get install -y postgresql postgresql-client
    - sudo service postgresql start  # Start the PostgreSQL service
  command: |
    sudo service postgresql start  # Ensure PostgreSQL starts on command
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
