image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y postgresql-13 postgresql-client-13
      sudo service postgresql stop
      sudo sed -i 's/^#port = .*/port = 5434/' /etc/postgresql/13/main/postgresql.conf  # Change port to 5434
      sudo update-alternatives --set pg_ctl /usr/lib/postgresql/13/bin/pg_ctl
      sudo update-alternatives --set psql /usr/lib/postgresql/13/bin/psql
      sudo service postgresql start
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
