image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      sudo service postgresql start
      sudo mkdir -p /workspace/pgsql-data  # Persistent storage for PostgreSQL
      sudo chown -R gitpod:gitpod /workspace/pgsql-data
      sudo pg_ctlcluster 13 main start
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
